name: CD

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build & twine
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package (sdist + wheel)
        run: python -m build

      - name: Twine check
        run: python -m twine check dist/*

      - name: Publish to GitHub Packages (Python)
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          ORG_URL="https://api.github.com/orgs/${OWNER}/packages/pypi/upload"
          USER_URL="https://api.github.com/users/${OWNER}/packages/pypi/upload"

          echo "Trying org endpoint: $ORG_URL"
          python -m twine upload --repository-url "$ORG_URL" dist/* || (
            echo "Org endpoint failed, trying user endpoint: $USER_URL" &&
            python -m twine upload --repository-url "$USER_URL" dist/*
          )
